// Capture a short effects/mix audition in an isolated QA browser; no microphone access.
const {chromium}=require('playwright');
const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.RIFT_BROWSER||'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-angle=swiftshader']});try{
  const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5173/',{waitUntil:'networkidle'});await page.click('#practice');await page.keyboard.press('p');
  const result=await page.evaluate(async()=>{const s=window.__rift.sound;window.__rift.view.renderer.setAnimationLoop(null);await s.start();const destination=s.ctx.createMediaStreamDestination();s.compressor.connect(destination);const recorder=new MediaRecorder(destination.stream,{mimeType:'audio/webm;codecs=opus'}),chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);const finished=new Promise(resolve=>recorder.onstop=resolve);recorder.start();let tick=0;const musicInterval=setInterval(()=>s.update(true,tick>30?3:0,tick>=16&&tick<28?(tick-16)/9:0,tick>50?3:1),25);const interval=setInterval(()=>{if(tick<12&&tick%2===0)s.event({type:'shoot',weapon:'PULSE',x:-4});if(tick>=12&&tick<16)s.event({type:'shoot',weapon:'SPREAD',x:-2});if(tick===28)s.event({type:'charge'});if(tick===35)s.event({type:'kill',boss:false,x:3});if(tick>38&&tick<50&&tick%2===0)s.event({type:'shoot',weapon:'LANCE',x:-3});if(tick>=50&&tick<80){if(tick%2===0)s.event({type:'vector',level:3,x:-4});if(tick%5===0)s.event({type:'missile',level:3,x:-4});if(tick%2===0)s.event({type:'shoot',weapon:'RING',level:3,x:-4});s.event({type:'shoot',weapon:tick%2?'SPREAD':'LANCE',level:3,x:-4});s.event({type:'impact',boss:true,x:4});if(tick%3===0)for(let i=0;i<6;i++)s.event({type:'kill',boss:false,x:-5+i*2});}if(tick===54)s.event({type:'boss'});if(tick===65)s.event({type:'bomb'});if(tick===80)s.event({type:'laserWarning',x:5});if(tick===95)s.event({type:'laser',x:5});if(tick===110){s.event({type:'kill',boss:true,x:4});s.event({type:'end',won:true});}tick++;},100);await new Promise(resolve=>setTimeout(resolve,16000));clearInterval(interval);clearInterval(musicInterval);s.update(false,0,0);recorder.stop();await finished;s.compressor.disconnect(destination);const array=await new Blob(chunks,{type:'audio/webm'}).arrayBuffer();const decoded=await s.ctx.decodeAudioData(array.slice(0));let peak=0,sum=0,clipped=0;const samples=decoded.getChannelData(0);for(const v of samples){peak=Math.max(peak,Math.abs(v));sum+=v*v;if(Math.abs(v)>.999)clipped++;}
    const wav=new ArrayBuffer(44+samples.length*2),dv=new DataView(wav),text=(o,str)=>{for(let i=0;i<str.length;i++)dv.setUint8(o+i,str.charCodeAt(i));};text(0,'RIFF');dv.setUint32(4,36+samples.length*2,true);text(8,'WAVEfmt ');dv.setUint32(16,16,true);dv.setUint16(20,1,true);dv.setUint16(22,1,true);dv.setUint32(24,decoded.sampleRate,true);dv.setUint32(28,decoded.sampleRate*2,true);dv.setUint16(32,2,true);dv.setUint16(34,16,true);text(36,'data');dv.setUint32(40,samples.length*2,true);samples.forEach((v,i)=>dv.setInt16(44+i*2,Math.max(-32768,Math.min(32767,Math.round(v*32767))),true));
    return {bytes:Array.from(new Uint8Array(array)),wav:Array.from(new Uint8Array(wav)),stats:{peak,rms:Math.sqrt(sum/samples.length),clipped,duration:decoded.duration,sampleRate:decoded.sampleRate}};});
  fs.mkdirSync('.artifacts',{recursive:true});fs.writeFileSync('.artifacts/combat-audio.webm',Buffer.from(result.bytes));fs.writeFileSync('.artifacts/combat-audio.wav',Buffer.from(result.wav));fs.writeFileSync('.artifacts/audio-stats.json',JSON.stringify(result.stats,null,2));console.log(JSON.stringify({errors,...result.stats}));if(errors.length)throw new Error(errors.join('\n'));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
