import test from 'node:test';
import assert from 'node:assert/strict';
import { Game, segmentHits } from '../src/game.js';
const step=(g,seconds,input={})=>{for(let i=0;i<seconds*90;i++)g.update(1/90,input);};
test('motion is bounded, frame independent, and diagonals are normalized',()=>{const a=new Game(),b=new Game();step(a,.2,{x:1});step(b,.2,{x:1,y:1});assert.ok(Math.abs(Math.hypot(b.player.x+4.8,b.player.y)-(a.player.x+4.8))<1e-9);step(a,10,{x:1,y:1});assert.equal(a.player.x,7.6);assert.equal(a.player.y,4.2);});
test('firing is deliberate; swept collisions cannot tunnel through targets',()=>{const g=new Game();step(g,1);assert.equal(g.shots.length,0);g.update(1/90,{fire:true});assert.ok(g.shots.some(s=>!s.hostile));assert.equal(segmentHits(-2,0,2,0,0,0,.1),true);assert.equal(segmentHits(-2,1,2,1,0,0,.1),false);});
test('all five power-ups work and duplicate weapons upgrade',()=>{const g=new Game();for(const kind of ['SPREAD','SPREAD','SHIELD','ECHO','BOMB'])g.collect({kind});assert.equal(g.player.weapon,'SPREAD');assert.equal(g.player.level,2);assert.equal(g.player.shield,2);assert.equal(g.player.echo,true);assert.equal(g.bombs,3);g.collect({kind:'LANCE'});assert.equal(g.player.weapon,'LANCE');assert.equal(g.player.level,1);});
test('invulnerability prevents stacked damage and shield takes first hit',()=>{const g=new Game();g.player.invincible=0;g.player.shield=1;g.hurtPlayer();g.hurtPlayer();assert.equal(g.player.hp,5);assert.equal(g.player.shield,0);step(g,2);g.hurtPlayer();assert.equal(g.player.hp,4);});
test('pulse bomb clears bullets and cancels a boss laser; holding spends only one',()=>{const g=new Game();g.spawnBoss();g.boss.entry=0;g.boss.warning=1;g.boss.laser=1;g.addShot(0,0,-1,0,true);step(g,.1,{bomb:true});assert.equal(g.bombs,1);assert.equal(g.shots.filter(s=>s.hostile).length,0);assert.equal(g.boss.laser,0);assert.equal(g.boss.warning,0);});
test('charged lance only damages cores in its 2D lane',()=>{const g=new Game();g.spawnEnemy('sentinel',0);g.spawnEnemy('sentinel',2);g.enemies.forEach(e=>{e.entry=0;e.x=2;e.hp=50;});g.player.charge=1.4;g.releaseCharge();assert.equal(g.enemies[0].hp,12);assert.equal(g.enemies[1].hp,50);assert.equal(g.player.charge,0);});
test('miniboss, boss, phase transitions, and victory are reachable',()=>{const g=new Game();g.time=66;g.nextWave=999;g.update(1/90);assert.equal(g.boss.type,'gatekeeper');g.boss.entry=0;for(const p of g.boss.parts)g.damageBossPart(g.boss,p,p.hp);g.damageEnemy(g.boss,1000,{core:true});assert.equal(g.boss,null);g.time=180;g.update(1/90);assert.equal(g.boss.type,'cathedral');g.boss.entry=0;g.boss.hp=g.boss.maxHp*.55;g.update(1/90);assert.equal(g.boss.phase,2);g.boss.hp=g.boss.maxHp*.2;g.update(1/90);assert.equal(g.boss.phase,3);for(const p of g.boss.parts)g.damageBossPart(g.boss,p,p.hp);g.damageEnemy(g.boss,1000,{core:true});assert.equal(g.state,'won');assert.ok(g.score>=12500);});
test('boss laser is telegraphed before it damages and stays on plane',()=>{const g=new Game();g.spawnBoss();const b=g.boss;b.entry=0;b.pattern=3;b.fire=0;g.player.invincible=0;g.update(1/90);assert.ok(b.warning>1);assert.equal(g.player.hp,5);step(g,1.6);assert.equal(g.player.hp,4);assert.equal('z' in g.player,false);assert.equal('z' in b,false);});
test('reset clears combat and ended games stop updating',()=>{const g=new Game();g.player.invincible=0;g.player.hp=1;g.hurtPlayer();assert.equal(g.state,'lost');const t=g.time;step(g,2,{fire:true});assert.equal(g.time,t);g.reset();assert.equal(g.state,'playing');assert.equal(g.player.hp,5);assert.equal(g.time,0);assert.equal(g.enemies.length,0);});
test('long run keeps separate projectile budgets bounded and seeded waves deterministic',()=>{const a=new Game(23),b=new Game(23);for(let i=0;i<90*240;i++){for(const g of [a,b]){g.player.invincible=10;g.update(1/90,{fire:true,y:Math.sin(i*.01)});g.drainEvents();}assert.ok(a.shots.filter(s=>s.hostile).length<=900);assert.ok(a.shots.filter(s=>!s.hostile).length<=240);}assert.equal(a.score,b.score);assert.deepEqual(a.enemies,b.enemies);});
test('curtain leaves a traversable corridor wider than the focused ship',()=>{const g=new Game();g.curtain(1.25);const bullets=g.shots.filter(s=>s.hostile);assert.ok(bullets.length>=18);for(const s of bullets)assert.ok(Math.abs(s.y-1.25)>.68);assert.ok(.68>g.player.r+bullets[0].r);});
test('focus slows movement without stopping deliberate fire',()=>{const g=new Game();step(g,.1,{x:1,focus:true,fire:true});assert.ok(Math.abs(g.player.x+4.8-.24)<1e-8);assert.equal(g.player.focus,true);assert.ok(g.shots.some(s=>!s.hostile));});
test('busy opening creates overlapping patterns and distinct projectile families',()=>{const g=new Game();let peak=0;for(let i=0;i<90*30;i++){g.player.invincible=10;g.update(1/90);g.drainEvents();peak=Math.max(peak,g.shots.filter(s=>s.hostile).length);}assert.ok(peak>=80,`Peak ${peak} is too sparse`);assert.ok(new Set(g.shots.filter(s=>s.hostile).map(s=>s.kind)).size>=2);});
test('corridor window suppresses unrelated aimed emitters',()=>{const g=new Game();g.time=12;g.spawnEnemy('sentinel',0);g.enemies[0].entry=0;g.enemies[0].x=5;g.enemies[0].fire=0;g.update(1/90);assert.equal(g.attackWindow,'corridor');assert.ok(g.shots.length>0);assert.ok(g.shots.every(s=>s.kind==='needle'&&s.vy===0));});
test('hostile budget cannot suppress player weapons',()=>{const g=new Game();for(let i=0;i<1000;i++)g.addShot(7,3,-1,0,true);assert.equal(g.shots.length,900);g.shootPlayer();assert.ok(g.shots.some(s=>!s.hostile));assert.ok(g.shots.length<=1140);});

test('weapon upgrades increase output and provide distinct rail formations',()=>{const g=new Game();g.player.weapon='SPREAD';g.player.level=1;g.shootPlayer();const low=g.shots.reduce((n,s)=>n+s.damage,0);g.shots=[];g.player.level=3;g.shootPlayer();assert.ok(g.shots.reduce((n,s)=>n+s.damage,0)>low*1.5);assert.ok(g.shots.length>=7);g.shots=[];g.player.weapon='LANCE';g.player.level=2;g.shootPlayer();assert.equal(g.shots.filter(s=>s.kind==='rail').length,2);});
test('unfinished Gatekeeper defers act changes and procession setpieces',()=>{const g=new Game();g.time=89;g.miniSpawned=true;g.spawnBoss(true);g.player.invincible=999;step(g,25);assert.equal(g.act,1);assert.equal(g.setpieces.has(108),false);assert.equal(g.boss.type,'gatekeeper');g.boss.entry=0;for(const p of g.boss.parts)g.damageBossPart(g.boss,p,p.hp);g.damageEnemy(g.boss,9999,{core:true});step(g,2);assert.equal(g.act,2);});
test('graze chain rewards risk and damage resets the multiplier',()=>{const g=new Game();g.player.invincible=0;for(let i=0;i<8;i++){g.addShot(g.player.x+.2,g.player.y+.2,0,0,true);g.update(1/90);}assert.ok(g.combo>1);assert.ok(g.score>80);g.hurtPlayer();assert.equal(g.combo,1);});


test('last opening is an isolated traversable corridor with a protected reading beat',()=>{const g=new Game();g.spawnBoss();const b=g.boss;b.entry=0;b.hp=180;b.phase=3;b.pattern=0;b.fire=0;b.spiral=0;g.player.invincible=999;g.addShot(-2,1,-1,0,true,1,'petal');g.update(1/90);assert.equal(b.attackName,'THE LAST OPENING');assert.ok(g.shots.filter(s=>s.hostile).every(s=>s.kind==='needle'&&Math.abs(s.y-g.player.y)>.68));const ids=g.shots.map(s=>s.id);step(g,.5);assert.deepEqual(g.shots.map(s=>s.id),ids);});
test('orrery phase has distinct concentric projectile families and recovery',()=>{const g=new Game();g.spawnBoss();const b=g.boss;b.entry=0;b.hp=b.maxHp*.55;b.phase=2;b.pattern=0;b.fire=0;b.spiral=0;g.player.invincible=999;g.update(1/90);assert.equal(b.attackName,'THE ORRERY');assert.ok(g.shots.some(s=>s.kind==='orb'));assert.ok(g.shots.some(s=>s.kind==='petal'));const count=g.shots.length;step(g,.5);assert.equal(g.shots.length,count);});
