import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {placeArena,RoomLock} from '../src/room.js';
const fit={width:3.8,distance:2.1};
const matrix=(x=0,y=0,z=0,yaw=0)=>new T.Matrix4().compose(new T.Vector3(x,y,z),new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),yaw),new T.Vector3(1,1,1));
const close=(a,b)=>assert.ok(a.elements.every((v,i)=>Math.abs(v-b.elements[i])<1e-9));
const pose=(yaw=0)=>({transform:{position:{x:1,y:1.7,z:2},orientation:new T.Quaternion().setFromEuler(new T.Euler(.2,yaw,.12,'YXZ'))}});
const create=()=>{const root=new T.Group();placeArena(root,pose(),fit);let lost=0,changed=0;const space=new EventTarget(),lock=new RoomLock(root,{onLost:()=>lost++,onChange:()=>changed++,makeTransform:(p,q)=>({position:p,orientation:q})});lock.connect(space);lock.placed();return{root,lock,space,get lost(){return lost;},get changed(){return changed;}};};
const anchor=()=>({anchorSpace:{},deleted:0,delete(){this.deleted++;}});
const reset=(space,m)=>{const e=new Event('reset');e.transform=m?{matrix:m.elements}:null;space.dispatchEvent(e);};
test('placement is square to horizontal gaze and ignores head pitch and roll',()=>{
 for(const yaw of [-1.1,0,.7]){const root=new T.Group(),p=pose(yaw);assert.equal(placeArena(root,p,fit),true);const forward=new T.Vector3(0,0,-1).applyQuaternion(p.transform.orientation).setY(0).normalize(),head=new T.Vector3(1,1.7,2);assert.ok(root.position.clone().sub(head).distanceTo(forward.multiplyScalar(fit.distance))<1e-10);assert.ok(Math.abs(root.rotation.x)+Math.abs(root.rotation.z)<1e-10);const a=root.localToWorld(new T.Vector3(-8,0,0)),b=root.localToWorld(new T.Vector3(8,0,0));assert.ok(Math.abs(a.distanceTo(head)-b.distanceTo(head))<1e-10);}
});
test('placement rejects emulated, invalid, and vertical gaze without corrupting arena',()=>{const root=new T.Group();placeArena(root,pose(),fit);const before=root.matrix.clone();for(const p of [null,{...pose(),emulatedPosition:true},{transform:{position:{x:NaN},orientation:{}}},{transform:{position:{x:1,y:1.7,z:2},orientation:new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),Math.PI/2)}}])assert.equal(placeArena(root,p,fit),false);close(root.matrix,before);});
test('known 30 degree origin reset preserves physical placement including scale',()=>{const t=create(),before=t.root.matrix.clone(),delta=matrix(.7,.1,-.3,Math.PI/6);reset(t.space,delta);close(delta.clone().multiply(t.root.matrix),before);assert.equal(t.lost,0);assert.equal(t.changed,1);});
test('unknown fallback reset pauses once and requires explicit recenter',()=>{const t=create();t.lock.update({});reset(t.space);reset(t.space);assert.equal(t.lost,1);assert.equal(t.lock.requiresRecenter,true);assert.equal(t.lock.update({}),false);t.lock.placed();assert.equal(t.lock.lost,false);assert.equal(t.lock.requiresRecenter,false);});
test('unsupported anchors preserve fixed arena and are not retried every frame',()=>{const t=create(),before=t.root.matrix.clone();for(let i=0;i<6000;i++)assert.equal(t.lock.update({}),true);close(t.root.matrix,before);assert.equal(t.lock.mode,'reference');});
test('native anchor follows coordinate corrections over 6000 frames without following the head',async()=>{const t=create(),a=anchor(),physical=t.root.matrix.clone(),scale=t.root.scale.clone();let calls=0;t.lock.update({createAnchor:()=>{calls++;return Promise.resolve(a);}});await t.lock.pending;const anchorPhysical=physical.clone().scale(new T.Vector3(1/scale.x,1/scale.y,1/scale.z));for(let i=0;i<6000;i++){const delta=matrix(i/20000,0,0,i/5999*Math.PI/6),reported=delta.clone().invert().multiply(anchorPhysical);assert.equal(t.lock.update({getPose:(s,r)=>{assert.equal(s,a.anchorSpace);assert.equal(r,t.space);return{transform:{matrix:reported.elements}};}}),true);close(delta.clone().multiply(t.root.matrix),physical);}assert.equal(calls,1);assert.deepEqual(t.root.scale,scale);assert.equal(t.lost,0);});
test('missing or emulated anchor pose pauses; recovery does not request recenter',async()=>{const t=create(),a=anchor();t.lock.update({createAnchor:()=>a});await t.lock.pending;for(const p of [null,{emulatedPosition:true,transform:{matrix:matrix().elements}},{transform:{matrix:[1,2]}}])assert.equal(t.lock.update({getPose:()=>p}),false);assert.equal(t.lost,1);reset(t.space);assert.equal(t.lock.requiresRecenter,false);assert.equal(t.lock.update({getPose:()=>({transform:{matrix:matrix().elements}})}),true);assert.equal(t.lock.lost,false);});
test('recenter and exit delete both active and late-created anchors',async()=>{for(const dispose of [false,true]){const t=create(),a=anchor();let resolve;t.lock.update({createAnchor:()=>new Promise(r=>resolve=r)});const pending=t.lock.pending;if(dispose)t.lock.dispose();else t.lock.placed();resolve(a);await pending;assert.equal(a.deleted,1);assert.equal(t.lock.anchor,null);}const t=create(),a=anchor();t.lock.update({createAnchor:()=>a});await t.lock.pending;t.lock.dispose();t.lock.dispose();assert.equal(a.deleted,1);});
test('anchor denial gracefully falls back without retry storms',async()=>{const t=create();let calls=0;const frame={createAnchor:()=>{calls++;return Promise.reject(new Error('unsupported'));}};t.lock.update(frame);await t.lock.pending;for(let i=0;i<100;i++)t.lock.update(frame);assert.equal(calls,1);assert.equal(t.lock.mode,'reference');assert.equal(t.lost,0);});
test('space replacement invalidates pending anchors; dispose removes reset listener',async()=>{const t=create(),a=anchor();let resolve;t.lock.update({createAnchor:()=>new Promise(r=>resolve=r)});const pending=t.lock.pending;t.lock.connect(new EventTarget());resolve(a);await pending;assert.equal(a.deleted,1);assert.equal(t.lock.requiresRecenter,true);t.lock.dispose();reset(t.space);assert.equal(t.lock.mode,'unplaced');});
