// Real animation-loop capture; scripted scene setup skips time, never changes rendering or hit rules.
const {chromium}=require('playwright');const fs=require('fs');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-angle=swiftshader']});const ctx=await browser.newContext({viewport:{width:1440,height:1000}});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.stack));
const evidence=[];async function capture(name){await page.screenshot({path:'.artifacts/'+name+'.png'});evidence.push(await page.evaluate(name=>{const{game:g,view:v}=window.__rift;return{name,time:g.time,act:g.act,state:g.state,draws:v.renderer.info.render.calls,triangles:v.renderer.info.render.triangles,hostiles:g.shots.filter(s=>s.hostile).length,particles:v.particles.length,cinematics:v.cinematics.map(c=>({kind:c.kind,age:c.age})),overlay:!document.getElementById('overlay').hidden};},name));}
async function scene(code){await page.evaluate(code);await page.keyboard.down('Space');}
try{await page.goto('http://localhost:5173/',{waitUntil:'networkidle'});await page.click('#practice');await page.evaluate(()=>{const{view:v,sound:s}=window.__rift;const output=document.createElement('canvas');output.width=v.renderer.domElement.width;output.height=v.renderer.domElement.height;const paint=output.getContext('2d');window.__recordActive=true;function composite(){if(!window.__recordActive)return;paint.fillStyle='#08121e';paint.fillRect(0,0,output.width,output.height);paint.drawImage(v.renderer.domElement,0,0);requestAnimationFrame(composite);}composite();const stream=output.captureStream(30),destination=s.ctx.createMediaStreamDestination();s.compressor.connect(destination);stream.addTrack(destination.stream.getAudioTracks()[0]);window.__captureChunks=[];window.__captureRecorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:4000000});window.__captureRecorder.ondataavailable=e=>window.__captureChunks.push(e.data);window.__captureRecorder.start();});
await scene(()=>{const{game:g}=window.__rift;g.player.invincible=999;for(let i=0;i<90*23;i++)g.update(1/90,{fire:true});g.drainEvents();});await page.keyboard.down('ArrowUp');await page.waitForTimeout(700);await page.keyboard.up('ArrowUp');await capture('act-one');await page.waitForTimeout(1500);
await page.keyboard.down('Shift');await page.waitForTimeout(1550);await capture('charge-ready');await page.keyboard.up('Shift');await page.waitForTimeout(90);await capture('charge-release');await page.keyboard.press('e');await page.waitForTimeout(120);await capture('bomb');await page.evaluate(()=>{const{view:v}=window.__rift;v.event({type:'setpiece',name:'LEVIATHAN',act:1});const e=v.cinematics.at(-1);e.obj.position.x=1;e.obj.position.y=1.7;});await page.waitForTimeout(600);await capture('leviathan');
await scene(()=>{const{game:g,view:v}=window.__rift;g.reset();v.clear();g.player.invincible=999;g.time=66;g.miniSpawned=true;g.spawnBoss(true);});await page.waitForTimeout(1600);await capture('gate-entry');await page.waitForTimeout(2300);await capture('gate-action');await page.evaluate(()=>{window.__rift.game.boss.hp=35;});await page.waitForTimeout(500);await capture('gate-phase-three');await page.evaluate(()=>{const g=window.__rift.game;g.damageEnemy(g.boss,9999);});await page.waitForTimeout(700);await capture('gate-collapse');await page.waitForTimeout(2200);
await scene(()=>{const{game:g,view:v}=window.__rift;g.reset();v.clear();g.player.invincible=999;g.time=107;g.setpieces=new Set([30]);g.miniSpawned=true;g.act=2;g.nextWave=108;g.nextPickup=110;});await page.waitForTimeout(6500);await capture('act-two-procession');await page.waitForTimeout(1600);
await scene(()=>{const{game:g,view:v}=window.__rift;g.reset();v.clear();g.player.invincible=999;g.time=149;g.setpieces=new Set([30,108]);g.act=3;g.miniSpawned=true;g.nextWave=150;g.nextPickup=152;g.player.weapon='LANCE';g.player.level=3;});await page.waitForTimeout(6500);await capture('act-three-helix');await page.waitForTimeout(1000);
await scene(()=>{const{game:g,view:v}=window.__rift;g.reset();v.clear();g.player.invincible=999;g.time=180;g.miniSpawned=true;g.bossSpawned=true;g.act=3;g.spawnBoss();});await page.waitForTimeout(1500);await capture('cathedral-entry');await page.waitForTimeout(2300);await page.evaluate(()=>{window.__rift.game.boss.hp=420;});await page.waitForFunction(()=>window.__rift.game.boss?.attackName==='THE ORRERY'&&window.__rift.game.shots.some(s=>s.hostile&&s.kind==='orb'),{},{timeout:15000});await page.waitForTimeout(450);await capture('cathedral-phase-two');
await page.evaluate(()=>{const g=window.__rift.game;g.boss.hp=180;g.boss.pattern=3;g.boss.fire=0;});await page.waitForFunction(()=>window.__rift.game.boss?.warning>0,{},{timeout:12000});await capture('laser-warning');await page.waitForFunction(()=>window.__rift.game.boss?.laser>0,{},{timeout:12000});await capture('laser-fire');await page.waitForTimeout(1600);await capture('cathedral-phase-three');
await page.evaluate(()=>{const g=window.__rift.game;g.damageEnemy(g.boss,9999);});await page.waitForTimeout(1300);await capture('cathedral-collapse');assert.equal(evidence.at(-1).overlay,false);await page.waitForFunction(()=>!document.getElementById('overlay').hidden,{},{timeout:20000});await capture('victory');assert.equal(evidence.at(-1).overlay,true);
await page.click('#restart');await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>window.__rift.game.state),'playing');assert.equal(await page.locator('#chain').textContent(),'×1.0');
await page.keyboard.up('Space');const video=await page.evaluate(async()=>{const recorder=window.__captureRecorder;const end=new Promise(resolve=>recorder.onstop=resolve);recorder.stop();await end;window.__recordActive=false;return Array.from(new Uint8Array(await new Blob(window.__captureChunks).arrayBuffer()));});fs.writeFileSync('.artifacts/showcase.webm',Buffer.from(video));assert.deepEqual(errors,[]);fs.writeFileSync('.artifacts/motion-evidence.json',JSON.stringify({errors,evidence},null,2));console.log(JSON.stringify({errors,maxDraws:Math.max(...evidence.map(e=>e.draws)),maxTriangles:Math.max(...evidence.map(e=>e.triangles)),frames:evidence.length}));
}finally{await ctx.close();await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
